version: 2
env:
  - REPO={{ .Env.ACCOUNT }}.dkr.ecr.ca-central-1.amazonaws.com/discordbots
builds:
  - id: statisticsbot
    binary: statisticsbot
    dir: ./cmd/statisticsbot
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre:
        - dir: ./cmd/statisticsbot
          cmd: go mod tidy
checksum:
  name_template: "checksums.txt"
dockers:
  - id: statisticsbot-build
    ids:
      - statisticsbot
    goarch: amd64
    build_flag_templates:
      - "--build-arg=KIND=statisticsbot"
    image_templates:
      - "{{ .Env.REPO }}:{{ tolower .ProjectName }}-{{ .Version }}"
      - "{{ .Env.REPO }}:{{ tolower .ProjectName }}-latest"
    dockerfile: Dockerfile
docker_manifests:
  - name_template: "{{ .Env.REPO }}:{{ tolower .ProjectName }}-{{ .Version }}"
    image_templates:
      - "{{ .Env.REPO }}:{{ tolower .ProjectName }}-{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
