BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Messages" (
	"id"	INTEGER NOT NULL,
	"channel_id"	INTEGER NOT NULL,
	"author"	INTEGER NOT NULL,
	"content"	TEXT NOT NULL,
	"date"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Mentions" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"message_id"	INTEGER NOT NULL,
	"member_id"	INTEGER NOT NULL,
	FOREIGN KEY("message_id") REFERENCES "Messages"("id")
);
CREATE TABLE IF NOT EXISTS "Channels" (
	"id"	INTEGER NOT NULL,
	"guild_id"	INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY("guild_id") REFERENCES "Guilds"("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Guilds" (
	"id"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
COMMIT;
