# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        required_providers {
            
            aws = {
            source  = "hashicorp/aws"
            version = "~> 5.24.0"
            }
            
            
            
            kubernetes = {
            version = "~> 2.23.0"
            source  = "hashicorp/kubernetes"
            }
            
        }
        required_version = ">= 1.2.2"
    }
