# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        required_providers {
            
            aws = {
            source  = "hashicorp/aws"
            version = "~> 5.100.0"
            }
            
            
            hcp = {
            version = "~> 0.108.0"
            source  = "hashicorp/hcp"
            }
            
            
            kubernetes = {
            version = "~> 2.37.0"
            source  = "hashicorp/kubernetes"
            }
            
            
            vault = {
                source  = "hashicorp/vault"
                version = "~> 3.25.0"
            }
            
        }
        required_version = ">= 1.2.2"
    }
