# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        required_providers {
            
            aws = {
            source  = "hashicorp/aws"
            version = "~> 6.2.0"
            }
            
            
            
            
        }
        required_version = ">= 1.2.2"
    }
