# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {

    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.2.0"
    }

    helm = {
      version = "~> 3.0.0"
      source  = "hashicorp/helm"
    }

    kubernetes = {
      version = "~> 2.23.0"
      source  = "hashicorp/kubernetes"
    }


  }
  required_version = ">= 1.2.2"
}
